sudo: false
language: perl
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"

env:
  - TEST_LIVE=0
  - TEST_LIVE=1

before_install:
  - ./dev-bin/travis-prepare.sh
script:
  PERL5OPT=-MDevel::Cover prove -lv t && cover -report coveralls

matrix:
  fast_finish: false # set to true to stop smoking at the first failure

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true
