name: coverage

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5.32' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: cpanm --quiet --notest --installdeps .
      - run: cpanm --quiet --notest App::Yath Devel::Cover Devel::Cover::Report::Coveralls
      - run: PERL5OPT=-MDevel::Cover yath test --qvf t/
        env:
          TEST_LIVE: 1
      - run: cover -report coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
