name: coverage

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: 'ubuntu-latest'
    name: Coverage
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: 5.32
      - run: cpanm --quiet --notest --installdeps .
      - run: cpanm --quiet --notest App::Yath Devel::Cover Devel::Cover::Report::Coveralls
      - run: PERL5OPT=-MDevel::Cover yath test --qvf t/
        env:
          TEST_LIVE: 1
      - run: cover -report coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
